{% set name = "molecular-rectifier" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/molecular_rectifier-{{ version }}.tar.gz
  sha256: 2401494527badf3bb7348f22227f99bb44c282baac13e20adeaa11aa4fc65bd6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - rdkit

test:
  imports:
    - molecular_rectifier
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/matteoferla/molecular_rectifier
  summary: Given an RDKit molecule that does not sanitise, correct it until it does, regardless of the severity of the change.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
